//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UserLaundry;

namespace UserLaundry
{
    using System;
    using System.Collections.Generic;

    public partial class LaundryRoom
    {
        public LaundryRoom()
        {
            this.LaundryUsers = new HashSet<LaundryUser>();
            this.Machines = new HashSet<Machine>();
            this.WashTimes = new HashSet<WashTime>();
        }

        public string name { get; set; }
        public Nullable<int> maxReservationPerUser { get; set; }

        public virtual ICollection<LaundryUser> LaundryUsers { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<WashTime> WashTimes { get; set; }


        public List<Machine> GetMachinesInUse()
        {
            List<Machine> list = new List<Machine>();
            foreach (var machine in Machines)
            {
                if (machine.start.GetValueOrDefault())
                {
                    list.Add(machine);
                }
            }
            return list;
        }

        public List<Machine> FindMachinesAvailable(Reservation reservation)
        {
            List<Machine> machines = Machines.ToList();
            if (!maxAmountOffRes()) {
            foreach (var m in Machines)
            {
                if (!m.broken.GetValueOrDefault())
                {
                    foreach (var res in m.Reservations)
                    {

                        if (res.reservationDate == reservation.reservationDate &&
                            res.WashTime == reservation.WashTime && !res.inactive.GetValueOrDefault())
                        {
                            if (machines.Contains(m))
                            {
                                machines.Remove(m);
                            }
                        }


                    }
                }
            }
            }

            return machines;
        }

        public bool maxAmountOffRes()
        {
            bool max = false;

            return max;
        }

        public override string ToString()
        {
            return name;
        }
    }
}

