//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLaundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.MachinePrograms = new HashSet<MachineProgram>();
            this.WrapperMachineRes = new HashSet<WrapperMachineRe>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int id { get; set; }
        public string machineType { get; set; }
        public Nullable<int> timesUsed { get; set; }
        public string LaundryRoom { get; set; }
        public Nullable<bool> broken { get; set; }
    
        public virtual LaundryRoom LaundryRoom1 { get; set; }
        public virtual ICollection<MachineProgram> MachinePrograms { get; set; }
        public virtual ICollection<WrapperMachineRe> WrapperMachineRes { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
