//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLaundry
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaundryDBEntities1 : DbContext
    {
        public LaundryDBEntities1()
            : base("name=LaundryDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LaundryRoom> LaundryRooms { get; set; }
        public DbSet<LaundryUser> LaundryUsers { get; set; }
        public DbSet<Machine> Machines { get; set; }
        public DbSet<MachineProgram> MachinePrograms { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<StartedWashCost> StartedWashCosts { get; set; }
        public DbSet<WashTime> WashTimes { get; set; }
        public DbSet<WrapperMachineRe> WrapperMachineRes { get; set; }
    }
}
