//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLaundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartedWashCost
    {
        public int id { get; set; }
        public Nullable<int> Reservation { get; set; }
        public Nullable<int> MachineProgram { get; set; }
    
        public virtual MachineProgram MachineProgram1 { get; set; }
        public virtual Reservation Reservation1 { get; set; }
    }
}
